version: '2'
services:
    jhipstertodo-app:
        image: jhipstertodo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertodo-postgresql:5432/jHipsterToDo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertodo-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstertodo-postgresql
